/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_whzxt_android_lytfingerprint */

#ifndef _Included_cn_whzxt_android_lytfingerprint
#define _Included_cn_whzxt_android_lytfingerprint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSOpenDevice
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSOpenDevice
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSCloseDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSCloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSGetImage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSGetImage
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSGenChar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSGenChar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSRegModule
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSRegModule
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSStoreChar
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSStoreChar
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSSearch
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSSearch
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSUpImage
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSUpImage
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSImgData2BMP
 * Signature: ([BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSImgData2BMP
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSDelChar
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSDelChar
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    PSEmpty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_PSEmpty
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_whzxt_android_lytfingerprint
 * Method:    getnFinger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_whzxt_android_lytfingerprint_getnFinger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
